TEXT_TO_SPEECH_CHUNK_SIZE_SECONDS = 0.3  # making it ridiculius tests blocking
PER_CHUNK_ALLOWANCE_SECONDS = 0.3
ALLOWED_IDLE_TIME = 30
INCOMPLETE_SCALING_FACTOR = 1.5
MAX_SILENCE_DURATION = 0
NUM_RESTARTS = 5
