"""
These are fillers a non-talking listener may say when talking to a person on a phone to indicate they are listening and following the conversation, but not wanting to interrupt:
"""
IGNORED_WHILE_TALKING_FILLERS = [
    "uh",
    "um",
    "mmhm",
    "Mhmm",
    "mm-mm",
    "uh-uh",
    "uh-huh",
    "nuh-uh",
    "Hey",
    "Hm.",
    "Huh.",
    "Mm.",
    "Oh.",
    "Aha.",
    "Uh-huh.",
    "Mm-hmm.",
    "Uh-uh.",
    "Mhmm.",
    "Oof",
    "Whoa",
    "Woah",
    "Wow",
    "Eek",
    "Ahem",
    "Uh-hum",
    "Eh-heh",
    "Erm",
    "Er",
    "Eh",
    "Ah",
    # confirmatory
    "Yeah",
    "Okey",
    "Okay",
    "Interesting",
    "Right",
    "Really?",
    "Thanks",
    "Yes",
    "Yup",
    "Yeh",
    "Sure",
    "Agree",
    "That's right",
    "I see",
    "Understood",
    "Got it",
    "Go ahead",
    "I'm listening",
    "Perfect",
    "Excellent",
    "Definitely",
    "Exactly",
]
